### ISSUE TITLE
本家の凄い新モデル「CUNET」がリリースされました

### ISSUE THREAD

**Issue by 2ji3150** [lltcggie/waifu2x-caffe#132]
本家の新しいモデルがリリースされました。
https://github.com/nagadomi/waifu2x/releases/tag/v0.13.2
waifu-caffeの更新をお願い致します。

**Comment by Yolkis** [comment]
May be we can use it by converting original model to caffe model and replacing existing files?

**Comment by nagadomi** [comment]
I've confirmed that it works fine with my personally modified waifu2x-caffe.
However, Caffe bundled with the original waifu2x-caffe(this repo) is probably very slow because https://github.com/BVLC/caffe/pull/5548 (Changes to speedup CropLayer) have not been merged.

個人的に改変しているwaifu2x-caffeで動作することを確認していますが、オリジナルのwaifu2x-caffeにバンドルされているCaffeは https://github.com/BVLC/caffe/pull/5548 (CropLayerを高速化する変更) がマージされていないため、おそらくかなり遅いです。

拡大付きのモデルは[upcunet.prototxt](https://github.com/nagadomi/waifu2x/blob/master/appendix/caffe_prototxt/upcunet.prototxt)の構造で、拡大なしのノイズ除去モデルは[cunet.prototxt](https://github.com/nagadomi/waifu2x/blob/master/appendix/caffe_prototxt/cunet.prototxt)の構造になっています。

**Comment by Yolkis** [comment]
@nagadomi can you share it with us?

**Comment by nagadomi** [comment]
@Yolkis No, it contains some closed codes. :cry:

**Comment by lltcggie** [comment]
追加しました。
現在バンドルしているCaffeは最新のmasterをマージしているので BVLC/caffe#5548 もマージされているので速度の問題はないと思われます。

**Comment by 2ji3150** [comment]
いつもありがとうございます。
軽くベンチしてみましたが、cunetはwaifu2x-caffeではuprestより若干遅いって感じです。
rgb 処理時間: 00:00:04.635
uprgb 処理時間: 00:00:02.095
cunet 処理時間: 00:00:09.802
uprestnet 処理時間: 00:00:08.968

**Comment by nagadomi** [comment]
@2ji3150 
出力から削られるサイズが大きいので分割サイズを大きくしないと遅いかもしれないです。
upresnetと同様に分割サイズによって出力が微妙に変わります。
また分割サイズは4の倍数になっていないとエラーになると思います。

**Comment by 2ji3150** [comment]
@nagadomi 
コメントありがとうございます。
もう一度より多くの画像でベンチしました。

テスト画像解像度2560*1290 4枚
format:jpg
分割サイズ: 256
分割サイズとバッチサイズをいじってみましたがやはり大体似たような結果です。
環境: Windows 10 1809 + GTX1060 6GB + Cudnn 7.4.1 for CUDA 10

rgb 処理時間: 00:00:18.315
uprgb 処理時間: 00:00:09.574
upresnet10 処理時間: 00:00:12.148
cunet 処理時間: 00:00:27.626

**Comment by nagadomi** [comment]
Torchだと画像変換レベルではvgg_7(RGB)とあまり変わらないですが
Crop,Flatten,Eltwiseあたりの実装が違う部分の差があるのかもしれないです。
構造的には確かに遅そうで、そのベンチマークのほうが納得感はあります。
TorchのCUDAやcuDNNまわりはNVIDIAの人が書いてたのでブロックを連続的に変換するところで計算以外のメモリの非同期転送などで謎の速さがあるのかもしれないです。
