### ISSUE TITLE
8 bit vs 16 bit colour depth?

### ISSUE THREAD

**Issue by lolcocks123** [lltcggie/waifu2x-caffe#149]
Newbie question alert.

I obviously searched online regarding colour depth 8 bit and 16 bit and learned everything about it theoretically.

However, how much does it affect the image when viewing in real life?
I converted one image and saw no difference.

Is the difference not visible to the human eye?
I ask because I am colour blind, so I might not be able to view a difference, but others might.

**Comment by bluesky-dark** [comment]
I don't think there's much difference between 8 bit and 16 bit,at least I can't find the difference.

**Comment by LinLingxin** [comment]
This is my opinion, I don't know if it is right : Color depth is just for software to finish work. I think you have searched Google and other information you can find, you are right because human can not find the difference between 8bit and 16bit. It is because the 8 bit means 8bit R & 8bit G & 8bit B, 2^8*2^8*2^8=16777216, we can see that 8bit can make 16777216 different colors, but human's eye can not distinguish between colors in one complex color picture. Now, the display is mostly use 8 bit to output things , of course many first-class display can support higher color depth. 16bit is just for Photoshop and other software to analysis and compute.
Thank you.

**Comment by lolcocks123** [comment]
Thank you for the inputs everyone.
Issue solved.
