### ISSUE TITLE
Waifu2x-caffe not fully using GPU memory clock?

### ISSUE THREAD

**Issue by YukiSakuma** [lltcggie/waifu2x-caffe#28]
While using waifu2x-caffe (magnifying, denoising etc.) I noticed that memory clock is only reaching at 3005 MHz (1502.5 MHz). My GPU has a default memory clock of 1753MHz so it should reach (1753*2) 3506MHz on the sensors. I tried other benchmark programs like Heaven or Kombustor to test if the GPU is the problem but the memory clock reached 3506MHz.
Here is a snapshot of the reading on the memory clock while using waifu2x-caffe v1.1.3.2
(GPU-Z)
![wew](https://cloud.githubusercontent.com/assets/16185735/15623540/6de14846-24a7-11e6-99e0-1dca10e688c0.gif)
I also used NVIDIA inspector and while using waifu2x-caffe it only reaches Power state 'P-2'
In theory GPU Power state while using waifu2x-caffe should reach Power state 'P-0' 
Reference
P0/P1 - Maximum 3D performance
P2/P3 - Balanced 3D performance-power
http://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__gpupstate.html
https://devtalk.nvidia.com/default/topic/892842/one-weird-trick-to-get-a-maxwell-v2-gpu-to-reach-its-max-memory-clock-/
https://www.einsteinathome.org/forum_thread.php?id=11044

**Comment by chungexcy** [comment]
Yes. waifu2x-caffe is using CUDA as a GPGPU application. When CUDA is enable, the graphic card will stay in P2, and the memory clock will be locked to a lower state. The reason behind is the lower memory frequency can reduce the error rate in memory, where gaming doesn't require this stability and therefore can reach a higher frequency (P0, other lower state are p5 and p8). 

So TITAN X are running at 1652MHz in CUDA, 1733MHz in gaming, where Quadro M6000 are set to 1652mhz default rate as it is designed for CUDA, and Tesla M40 only have a 1500MHz clock for long term running, even with ECC enabled.

Also, you don't need to worry about it, because the memory bandwidth is not the bottleneck (your figure showing 31% of memory bandwidth). With nvidia-inspector, p2 memory frequency can be overclocked if you increase it under p2 tab, but you will not see a difference. If you would like to pursue a faster speed, just overclock the core frequency and you will see a linear speed-up.

**Comment by lltcggie** [comment]
@chungexcy さん、僕の代わりに回答していただきありがとうございます。
ちなみにNVIDIA Inspectorで変換中のP-Stateを確認したところ、こちらが使っているGPU(GTX 660)ではP0になっています。

**Comment by YukiSakuma** [comment]
Updating it just in case I did try to overclock my GPU +150 core it improves the speed but it's unstable on waifu2x-caffe I get "driver has stopped and recovered" sometimes when using waifu2x-caffe but this OC is stable on games or just maybe I just didn't win in the silicon lottery.
