### ISSUE TITLE
CUI Console error output not readable

### ISSUE THREAD

**Issue by Christian77777** [lltcggie/waifu2x-caffe#88]
Using Waifu2x-caffe-cui from a batch file worked well, but now I am typing in a command wrong or something, because I get a error immediately. The problem is the error is in gibberish that I cant understand or translate. 

> âGâëü[: âéâfâïâtâ@âCâïé¬èJé»é▄é╣é±é┼é╡é╜

This error I think is the same everytime I start the program with the broken script. But I don't know what to check anymore. While if its just a translation issue my computer doesn't know how to handle yet, I feel like if you have gone through the trouble of allowing different languages, you would want the output to be in the correct language as well. I have a little more detail posted here, before I realized it would be best if you could help. [http://stackoverflow.com/questions/43774526/windows-console-output-from-waifu2x-caffe-unintelligible](url)

**Comment by alemonmk** [comment]
The CUI does not do Unicode, for now use GUI with command line instead. See #87.

That gibberish is a string in Shift-JIS encoding displayed in Code Page 437.
It actually is `エラー: モデルファイルが開けませんでした`, check if there is a directory named `models` in wherever you put `waifu2x-caffe-cui` and the current working directory, because it can't find neural network models. Also try using the full path to the executable in your command.

Also, `--auto_start`,  `--auto_exit`, `--no_overwrite`, `-y` does not apply to CUI so you can omit those.

Note: not devs here.

**Comment by Christian77777** [comment]
Thank you very much for the help so far. Except now the GUI script outputs the images into /Desired Folder/"Desired Folder (parameters)(moreParameters)"/SourceFolder/ This is even though I set -o "Path\to\Desired" Is this intended, regardless of -o? The CUI version output to the right folder correctly. The translation of the readme is a little confusing.

**Comment by alemonmk** [comment]
Have you read that issue carefully you'll notice that -o in GUI behaves this way.

**Comment by Christian77777** [comment]
Ok, sorry I missed that the first time I read it, I hope the developer will implement your fix sooner then later, for both CUI unicode, and GUI output Folder
